### ISSUE TITLE
understanding crop.py

### ISSUE THREAD

**Issue by OneManArmy93** [PuneetSinmgh/VoxelNet_implementation#1]
Hello, im new to ML and im trying to reproduce this code.
Can anyone be gentle enough to explain the crop.py file please?
Also, i dont understand why loading the calib file but not the label file?
Thank you

**Comment by PuneetSinmgh** [comment]
crop.py intend to crop all the cloud points outside the image cordinates. Voxelnet focuses on converting 3D data into cloud points and then uses reinforcement learning to learn the shape of the 3D images. 
For more information go through this paper https://arxiv.org/abs/1711.06396

**Comment by OneManArmy93** [comment]
@PuneetSinmgh  thank you for your reply! but what is the point of cropping the data? Doesn't that impact the learning process regarding the image?
Also, what is the output of the voxelization? is it a 3D array (filled with 0 and 1) or something else? and can i be inspired by this voxelization process to teach a 3D CNN which takes a voxel grid as an input?
much appreciated

**Comment by PuneetSinmgh** [comment]
The idea is to crop the cloud points not the Image itself. So no loss of data.
The Voxels contain not just 0 and 1 , it contains float values. Voxelnet Architecture itself uses CNN for training and classification. Please go through the paper before diving into code.
